<?php

echo "<table align='center' border='0' bordercolor='#808080' cellpadding='0' cellspacing='0' style='border-collapse: collapse;' width='760'>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='40' height='20'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: solid; border-bottom-width: 1' bgcolor='#FFFFFF' width='680' height='20'>\n";
echo "<font size='2' color='#808080'>Plot data";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='40' height='20'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='40'>\n";
echo "      </td>\n";
echo "      <td valign='middle' align='left' style='border-color: #808080; border-left-style: solid; border-left-width: 1; border-right-style: solid; border-right-width: 1; border-top-style: none; border-top-width: 0; border-bottom-style: solid; border-bottom-width: 1' bgcolor='#FFFFFF' width='680'>\n";

echo "<form action='slowcontrol/SlowControlGraph.php' id='plot' class='fileform' method='post' enctype='multipart/form-data' onSubmit='return ckFormular()'>";
echo "<table align='center' border='0' bordercolor='#808080' cellpadding='0' cellspacing='0' style='border-collapse: collapse;' width='680'>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='100' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='50' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='490' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10' height='10'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='100'>\n";

echo "<input type='radio' name='plotOption' value='nHours' checked><font size='2'>Since n hours:</font>";

echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='50'>\n";

echo "<input type='text' style='width:25px; height:20px;' name='hours' maxlength='5'>";

echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='490'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='100'>\n";

echo "<input type='radio' name='plotOption' value='Date'><font size='2'>Time period:</font>";

echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='50'>\n";

echo "<font size='2'>From:&nbsp&nbsp</font>";

echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='490'>\n";

echo "<font size='2'>dd:&nbsp</font><select name='startDay'>";
echo "<option>01</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "<option>25</option>";
echo "<option>26</option>";
echo "<option>27</option>";
echo "<option>28</option>";
echo "<option>29</option>";
echo "<option>30</option>";
echo "<option>31</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp mm:&nbsp</font><select name='startMonth'>";
echo "<option>01</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp yyyy:&nbsp</font><select name='startYear'>";
echo "<option>2010</option>";
echo "<option>2011</option>";
echo "<option>2012</option>";
echo "<option>2013</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp HH:&nbsp</font><select name='startHour'>";
echo "<option>01</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp MM:&nbsp</font><select name='startMinute'>";
echo "<option>00</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "<option>25</option>";
echo "<option>26</option>";
echo "<option>27</option>";
echo "<option>28</option>";
echo "<option>29</option>";
echo "<option>30</option>";
echo "<option>31</option>";
echo "<option>32</option>";
echo "<option>33</option>";
echo "<option>34</option>";
echo "<option>35</option>";
echo "<option>36</option>";
echo "<option>37</option>";
echo "<option>38</option>";
echo "<option>39</option>";
echo "<option>40</option>";
echo "<option>41</option>";
echo "<option>42</option>";
echo "<option>43</option>";
echo "<option>44</option>";
echo "<option>45</option>";
echo "<option>46</option>";
echo "<option>47</option>";
echo "<option>48</option>";
echo "<option>49</option>";
echo "<option>50</option>";
echo "<option>51</option>";
echo "<option>52</option>";
echo "<option>53</option>";
echo "<option>54</option>";
echo "<option>55</option>";
echo "<option>56</option>";
echo "<option>57</option>";
echo "<option>58</option>";
echo "<option>59</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp SS:&nbsp</font><select name='startSecond'>";
echo "<option>00</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "<option>25</option>";
echo "<option>26</option>";
echo "<option>27</option>";
echo "<option>28</option>";
echo "<option>29</option>";
echo "<option>30</option>";
echo "<option>31</option>";
echo "<option>32</option>";
echo "<option>33</option>";
echo "<option>34</option>";
echo "<option>35</option>";
echo "<option>36</option>";
echo "<option>37</option>";
echo "<option>38</option>";
echo "<option>39</option>";
echo "<option>40</option>";
echo "<option>41</option>";
echo "<option>42</option>";
echo "<option>43</option>";
echo "<option>44</option>";
echo "<option>45</option>";
echo "<option>46</option>";
echo "<option>47</option>";
echo "<option>48</option>";
echo "<option>49</option>";
echo "<option>50</option>";
echo "<option>51</option>";
echo "<option>52</option>";
echo "<option>53</option>";
echo "<option>54</option>";
echo "<option>55</option>";
echo "<option>56</option>";
echo "<option>57</option>";
echo "<option>58</option>";
echo "<option>59</option>";
echo "</select>";

echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='100'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='50'>\n";

echo "<font size='2'>To:&nbsp&nbsp</font>";

echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='490'>\n";

echo "<font size='2'>dd:&nbsp</font><select name='endDay'>";
echo "<option>01</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "<option>25</option>";
echo "<option>26</option>";
echo "<option>27</option>";
echo "<option>28</option>";
echo "<option>29</option>";
echo "<option>30</option>";
echo "<option>31</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp mm:&nbsp</font><select name='endMonth'>";
echo "<option>01</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp yyyy:&nbsp</font><select name='endYear'>";
echo "<option>2010</option>";
echo "<option>2011</option>";
echo "<option>2012</option>";
echo "<option>2013</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp HH:&nbsp</font><select name='endHour'>";
echo "<option>01</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp MM:&nbsp</font><select name='endMinute'>";
echo "<option>00</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "<option>25</option>";
echo "<option>26</option>";
echo "<option>27</option>";
echo "<option>28</option>";
echo "<option>29</option>";
echo "<option>30</option>";
echo "<option>31</option>";
echo "<option>32</option>";
echo "<option>33</option>";
echo "<option>34</option>";
echo "<option>35</option>";
echo "<option>36</option>";
echo "<option>37</option>";
echo "<option>38</option>";
echo "<option>39</option>";
echo "<option>40</option>";
echo "<option>41</option>";
echo "<option>42</option>";
echo "<option>43</option>";
echo "<option>44</option>";
echo "<option>45</option>";
echo "<option>46</option>";
echo "<option>47</option>";
echo "<option>48</option>";
echo "<option>49</option>";
echo "<option>50</option>";
echo "<option>51</option>";
echo "<option>52</option>";
echo "<option>53</option>";
echo "<option>54</option>";
echo "<option>55</option>";
echo "<option>56</option>";
echo "<option>57</option>";
echo "<option>58</option>";
echo "<option>59</option>";
echo "</select>";

echo "<font size='2'>&nbsp&nbsp SS:&nbsp</font><select name='endSecond'>";
echo "<option>00</option>";
echo "<option>02</option>";
echo "<option>03</option>";
echo "<option>04</option>";
echo "<option>05</option>";
echo "<option>06</option>";
echo "<option>07</option>";
echo "<option>08</option>";
echo "<option>09</option>";
echo "<option>10</option>";
echo "<option>11</option>";
echo "<option>12</option>";
echo "<option>13</option>";
echo "<option>14</option>";
echo "<option>15</option>";
echo "<option>16</option>";
echo "<option>17</option>";
echo "<option>18</option>";
echo "<option>19</option>";
echo "<option>20</option>";
echo "<option>21</option>";
echo "<option>22</option>";
echo "<option>23</option>";
echo "<option>24</option>";
echo "<option>25</option>";
echo "<option>26</option>";
echo "<option>27</option>";
echo "<option>28</option>";
echo "<option>29</option>";
echo "<option>30</option>";
echo "<option>31</option>";
echo "<option>32</option>";
echo "<option>33</option>";
echo "<option>34</option>";
echo "<option>35</option>";
echo "<option>36</option>";
echo "<option>37</option>";
echo "<option>38</option>";
echo "<option>39</option>";
echo "<option>40</option>";
echo "<option>41</option>";
echo "<option>42</option>";
echo "<option>43</option>";
echo "<option>44</option>";
echo "<option>45</option>";
echo "<option>46</option>";
echo "<option>47</option>";
echo "<option>48</option>";
echo "<option>49</option>";
echo "<option>50</option>";
echo "<option>51</option>";
echo "<option>52</option>";
echo "<option>53</option>";
echo "<option>54</option>";
echo "<option>55</option>";
echo "<option>56</option>";
echo "<option>57</option>";
echo "<option>58</option>";
echo "<option>59</option>";
echo "</select>";

echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10' height='25'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='100' height='25'>\n";

echo "<select id='selectVariable' name='variable' onchange='windowName()'>";
echo "<option>Variable</option>";
echo "<option>Grid</option>";
echo "<option>Leakage</option>";
echo "<option>Cathode</option>";
echo "<option>First</option>";
echo "<option>Pressure</option>";
echo "<option>Alarm</option>";
echo "<option>TC1</option>";
echo "<option>TC2</option>";
echo "<option>TC3</option>";
echo "</select>";

echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='50' height='25'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='490' height='25'>\n";

echo "<input type='submit' id='plotGraph' class='btn' style='width:80px; height:20px;' value='Submit'>";

echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10' height='25'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='100' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='50' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='left' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='490' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='10' height='10'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "</table>\n";
echo "</form>";

echo "      </td>\n";
echo "      <td valign='bottom' align='right' style='border-color: #808080; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='40'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "      <td valign='middle' align='left' style='border-color: #000000; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='40' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='middle' align='left' style='border-color: #000000; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='680' height='10'>\n";
echo "      </td>\n";
echo "      <td valign='middle' align='left' style='border-color: #000000; border-left-style: none; border-left-width: 0; border-right-style: none; border-right-width: 0; border-top-style: none; border-top-width: 0; border-bottom-style: none; border-bottom-width: 0' bgcolor='#FFFFFF' width='40' height='10'>\n";
echo "      </td>\n";
echo "   </tr>\n";
echo "</table>\n";

echo "<iframe src='slowcontrol/slowcontrol2.php' width='760' height='570' align='middle' frameborder='0' marginwidth='0' marginheight='0' scrolling='no'></iframe>";

?>
